# Generated by Django 5.0.2 on 2024-04-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admincol',
        ),
    ]
